.PHONY: compile release

SHELL = /bin/bash

HOME=/tmp
export HOME


compile:
	cd src && CGO_ENABLED=0 go build -o ../${BINARY}

release:
	tar --create --gzip --file ${BINARY}.tar.gz ${BINARY}


include Makefile.tests
